name: doxygen

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: doxygen-en
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'doxygen/vsf_doxygen_en.conf'

      - name: doxygen-zh
        uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: 'doxygen/vsf_doxygen_zh.conf'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.VSF_AIO }}
          external_repository: vsfteam/vsfteam.github.io
          publish_dir: doxygen
          publish_branch: master
