name: repository dispatch

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.VSF_AIO }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'vsf-linux',
              repo: 'vsf.linux',
              workflow_id: 'vsf-sync.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'vsfteam',
              repo: 'vsf.demo',
              workflow_id: 'vsf-sync.yml',
              ref: 'main'
            })

      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.VSF_AIO }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'vsfteam',
              repo: 'vsfteam-hub-mirror',
              workflow_id: 'gitee-sync.yml',
              ref: 'master'
            })
